#!/bin/bash
set -u
: "${CIVITAI_API_KEY:?CIVITAI_API_KEY must be set}"
KEY="$CIVITAI_API_KEY"
DEST=/root/ComfyUI/models/loras
mkdir -p "$DEST"
rm -f "$DEST/ass_krea2_loraholic.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/ass_krea2_loraholic.safetensors" "https://civitai.com/api/download/models/3072964" && echo "ok ass_krea2_loraholic.safetensors" || echo "FAIL ass_krea2_loraholic.safetensors"
rm -f "$DEST/age_krea2_loraholic.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/age_krea2_loraholic.safetensors" "https://civitai.com/api/download/models/3067659" && echo "ok age_krea2_loraholic.safetensors" || echo "FAIL age_krea2_loraholic.safetensors"
rm -f "$DEST/skintone_v2_krea2_loraholic.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/skintone_v2_krea2_loraholic.safetensors" "https://civitai.com/api/download/models/3187970" && echo "ok skintone_v2_krea2_loraholic.safetensors" || echo "FAIL skintone_v2_krea2_loraholic.safetensors"
rm -f "$DEST/Arcana_Press_-_Krea2.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/Arcana_Press_-_Krea2.safetensors" "https://civitai.com/api/download/models/3113777" && echo "ok Arcana_Press_-_Krea2.safetensors" || echo "FAIL Arcana_Press_-_Krea2.safetensors"
rm -f "$DEST/OHmega_style__Krea_2__epoch_10.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/OHmega_style__Krea_2__epoch_10.safetensors" "https://civitai.com/api/download/models/3087438" && echo "ok OHmega_style__Krea_2__epoch_10.safetensors" || echo "FAIL OHmega_style__Krea_2__epoch_10.safetensors"
rm -f "$DEST/krea2_Enhancer.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/krea2_Enhancer.safetensors" "https://civitai.com/api/download/models/3070143" && echo "ok krea2_Enhancer.safetensors" || echo "FAIL krea2_Enhancer.safetensors"
rm -f "$DEST/krea2_identity_edit_v1.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/krea2_identity_edit_v1.safetensors" "https://civitai.com/api/download/models/3107391" && echo "ok krea2_identity_edit_v1.safetensors" || echo "FAIL krea2_identity_edit_v1.safetensors"
rm -f "$DEST/90s_Grit_v01.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/90s_Grit_v01.safetensors" "https://civitai.com/api/download/models/3197607" && echo "ok 90s_Grit_v01.safetensors" || echo "FAIL 90s_Grit_v01.safetensors"
rm -f "$DEST/Krea2_TextFusion_Refusal_Reduction.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/Krea2_TextFusion_Refusal_Reduction.safetensors" "https://civitai.com/api/download/models/3125118" && echo "ok Krea2_TextFusion_Refusal_Reduction.safetensors" || echo "FAIL Krea2_TextFusion_Refusal_Reduction.safetensors"
rm -f "$DEST/ultra_real_krea2_v1.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/ultra_real_krea2_v1.safetensors" "https://civitai.com/api/download/models/3091374" && echo "ok ultra_real_krea2_v1.safetensors" || echo "FAIL ultra_real_krea2_v1.safetensors"
rm -f "$DEST/skin_tone_krea2.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/skin_tone_krea2.safetensors" "https://civitai.com/api/download/models/3086170" && echo "ok skin_tone_krea2.safetensors" || echo "FAIL skin_tone_krea2.safetensors"
rm -f "$DEST/lenovo_krea2.safetensors"
curl -sL --retry 5 --retry-delay 2 -H "Authorization: Bearer $KEY" -o "$DEST/lenovo_krea2.safetensors" "https://civitai.com/api/download/models/3075606" && echo "ok lenovo_krea2.safetensors" || echo "FAIL lenovo_krea2.safetensors"
